import { 
  Profile, 
  Teacher, 
  Student, 
  ClassRoom, 
  Subject, 
  Schedule, 
  Attendance, 
  Material, 
  Assignment, 
  Submission, 
  TeacherJournal, 
  AttitudeAssessment 
} from '../types/database';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-admin-1',
    nama: 'Rahmat Gobel, S.Pd',
    email: 'admin.tu@sman1batudaapantai.sch.id',
    role: 'admin',
    nomor_telepon: '081244556677',
    created_at: '2024-01-10T08:00:00Z',
  },
  {
    id: 'user-guru-1',
    nama: 'Dra. Nurhayati Daud, M.Pd',
    email: 'nurhayati.daud@sman1batudaapantai.sch.id',
    role: 'guru',
    nomor_telepon: '085299887711',
    created_at: '2024-01-10T08:00:00Z',
  },
  {
    id: 'user-guru-2',
    nama: 'Drs. Ismail Pomalingo',
    email: 'ismail.pomalingo@sman1batudaapantai.sch.id',
    role: 'guru',
    nomor_telepon: '081377665544',
    created_at: '2024-01-10T08:00:00Z',
  },
  {
    id: 'user-guru-3',
    nama: 'Fatmah Usman, S.Pd',
    email: 'fatmah.usman@sman1batudaapantai.sch.id',
    role: 'guru',
    nomor_telepon: '085311223344',
    created_at: '2024-01-10T08:00:00Z',
  },
  {
    id: 'user-siswa-1',
    nama: 'Moh. Fikri Hasan',
    email: 'fikri.hasan@siswa.sman1batudaapantai.sch.id',
    role: 'siswa',
    nomor_telepon: '082190011223',
    created_at: '2024-07-15T08:00:00Z',
  },
  {
    id: 'user-siswa-2',
    nama: 'Siti Rahmawati Djafar',
    email: 'siti.djafar@siswa.sman1batudaapantai.sch.id',
    role: 'siswa',
    nomor_telepon: '082190011224',
    created_at: '2024-07-15T08:00:00Z',
  },
  {
    id: 'user-siswa-3',
    nama: 'Fadly Ahmad',
    email: 'fadly.ahmad@siswa.sman1batudaapantai.sch.id',
    role: 'siswa',
    nomor_telepon: '082190011225',
    created_at: '2024-07-15T08:00:00Z',
  },
  {
    id: 'user-siswa-4',
    nama: 'Nurul Aini Otoluwa',
    email: 'nurul.otoluwa@siswa.sman1batudaapantai.sch.id',
    role: 'siswa',
    nomor_telepon: '082190011226',
    created_at: '2024-07-15T08:00:00Z',
  },
  {
    id: 'user-siswa-5',
    nama: 'Aditya Pratama Lihawa',
    email: 'aditya.lihawa@siswa.sman1batudaapantai.sch.id',
    role: 'siswa',
    nomor_telepon: '082190011227',
    created_at: '2024-07-15T08:00:00Z',
  }
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 't-1',
    profile_id: 'user-guru-1',
    nip: '196904121994122001',
    mapel_utama: 'Fisika & Informatika',
  },
  {
    id: 't-2',
    profile_id: 'user-guru-2',
    nip: '196508211991031008',
    mapel_utama: 'Matematika Peminatan',
  },
  {
    id: 't-3',
    profile_id: 'user-guru-3',
    nip: '198210152009022003',
    mapel_utama: 'Bahasa Indonesia',
  }
];

export const INITIAL_CLASSES: ClassRoom[] = [
  {
    id: 'c-xii-mipa-1',
    nama_kelas: 'XII MIPA 1',
    tingkat: 'XII',
    wali_kelas_id: 't-1',
    tahun_ajaran: '2024/2025',
  },
  {
    id: 'c-xii-mipa-2',
    nama_kelas: 'XII MIPA 2',
    tingkat: 'XII',
    wali_kelas_id: 't-2',
    tahun_ajaran: '2024/2025',
  },
  {
    id: 'c-xii-ips-1',
    nama_kelas: 'XII IPS 1',
    tingkat: 'XII',
    wali_kelas_id: 't-3',
    tahun_ajaran: '2024/2025',
  },
  {
    id: 'c-xi-mipa-1',
    nama_kelas: 'XI MIPA 1',
    tingkat: 'XI',
    tahun_ajaran: '2024/2025',
  },
  {
    id: 'c-x-1',
    nama_kelas: 'X-1 Merdeka',
    tingkat: 'X',
    tahun_ajaran: '2024/2025',
  }
];

export const INITIAL_SUBJECTS: Subject[] = [
  { id: 'sub-fisika', nama_mapel: 'Fisika', kode_mapel: 'FIS-XII', kelompok: 'Peminatan MIPA' },
  { id: 'sub-matematika', nama_mapel: 'Matematika Wajib', kode_mapel: 'MAT-W', kelompok: 'Wajib Umum' },
  { id: 'sub-biologi', nama_mapel: 'Biologi', kode_mapel: 'BIO-XII', kelompok: 'Peminatan MIPA' },
  { id: 'sub-kimia', nama_mapel: 'Kimia', kode_mapel: 'KIM-XII', kelompok: 'Peminatan MIPA' },
  { id: 'sub-indo', nama_mapel: 'Bahasa Indonesia', kode_mapel: 'BIND-XII', kelompok: 'Wajib Umum' },
  { id: 'sub-inggris', nama_mapel: 'Bahasa Inggris', kode_mapel: 'BING-XII', kelompok: 'Wajib Umum' },
  { id: 'sub-tik', nama_mapel: 'Informatika & TIK', kode_mapel: 'INF-XII', kelompok: 'Pilihan' },
  { id: 'sub-pai', nama_mapel: 'Pendidikan Agama & Budi Pekerti', kode_mapel: 'PAI-XII', kelompok: 'Wajib Umum' },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 's-1',
    profile_id: 'user-siswa-1',
    nis: '220101',
    nisn: '0068472918',
    kelas_id: 'c-xii-mipa-1',
    jenis_kelamin: 'L',
    alamat: 'Desa Kayubulan, Kec. Batudaa Pantai, Kab. Gorontalo',
  },
  {
    id: 's-2',
    profile_id: 'user-siswa-2',
    nis: '220102',
    nisn: '0068472919',
    kelas_id: 'c-xii-mipa-1',
    jenis_kelamin: 'P',
    alamat: 'Desa Lamu, Kec. Batudaa Pantai, Kab. Gorontalo',
  },
  {
    id: 's-3',
    profile_id: 'user-siswa-3',
    nis: '220103',
    nisn: '0068472920',
    kelas_id: 'c-xii-mipa-1',
    jenis_kelamin: 'L',
    alamat: 'Desa Bongo, Kec. Batudaa Pantai, Kab. Gorontalo',
  },
  {
    id: 's-4',
    profile_id: 'user-siswa-4',
    nis: '220104',
    nisn: '0068472921',
    kelas_id: 'c-xii-mipa-1',
    jenis_kelamin: 'P',
    alamat: 'Desa Olimoo\'o, Kec. Batudaa Pantai, Kab. Gorontalo',
  },
  {
    id: 's-5',
    profile_id: 'user-siswa-5',
    nis: '220105',
    nisn: '0068472922',
    kelas_id: 'c-xii-mipa-1',
    jenis_kelamin: 'L',
    alamat: 'Desa Tontayuo, Kec. Batudaa Pantai, Kab. Gorontalo',
  },
];

export const INITIAL_SCHEDULES: Schedule[] = [
  {
    id: 'sch-1',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-fisika',
    teacher_id: 't-1',
    hari: 'Senin',
    jam_mulai: '07:15',
    jam_selesai: '08:45',
    ruangan: 'Lab Fisika',
  },
  {
    id: 'sch-2',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-matematika',
    teacher_id: 't-2',
    hari: 'Senin',
    jam_mulai: '09:00',
    jam_selesai: '10:30',
    ruangan: 'R. XII MIPA 1',
  },
  {
    id: 'sch-3',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-tik',
    teacher_id: 't-1',
    hari: 'Rabu',
    jam_mulai: '07:15',
    jam_selesai: '08:45',
    ruangan: 'Lab Komputer',
  },
  {
    id: 'sch-4',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-indo',
    teacher_id: 't-3',
    hari: 'Kamis',
    jam_mulai: '10:45',
    jam_selesai: '12:15',
    ruangan: 'R. XII MIPA 1',
  },
  {
    id: 'sch-5',
    class_id: 'c-xii-mipa-2',
    subject_id: 'sub-fisika',
    teacher_id: 't-1',
    hari: 'Selasa',
    jam_mulai: '07:15',
    jam_selesai: '08:45',
    ruangan: 'Lab Fisika',
  },
];

export const INITIAL_ATTENDANCES: Attendance[] = [
  {
    id: 'att-1',
    student_id: 's-1',
    schedule_id: 'sch-1',
    class_id: 'c-xii-mipa-1',
    tanggal: '2025-02-24',
    status: 'Hadir',
    input_by: 'user-guru-1',
  },
  {
    id: 'att-2',
    student_id: 's-2',
    schedule_id: 'sch-1',
    class_id: 'c-xii-mipa-1',
    tanggal: '2025-02-24',
    status: 'Hadir',
    input_by: 'user-guru-1',
  },
  {
    id: 'att-3',
    student_id: 's-3',
    schedule_id: 'sch-1',
    class_id: 'c-xii-mipa-1',
    tanggal: '2025-02-24',
    status: 'Sakit',
    keterangan: 'Surat dokter puskesmas Batudaa Pantai',
    input_by: 'user-guru-1',
  },
  {
    id: 'att-4',
    student_id: 's-4',
    schedule_id: 'sch-1',
    class_id: 'c-xii-mipa-1',
    tanggal: '2025-02-24',
    status: 'Hadir',
    input_by: 'user-guru-1',
  },
  {
    id: 'att-5',
    student_id: 's-5',
    schedule_id: 'sch-1',
    class_id: 'c-xii-mipa-1',
    tanggal: '2025-02-24',
    status: 'Terlambat',
    keterangan: 'Kendala ombak/transportasi pesisir 10 menit',
    input_by: 'user-guru-1',
  },
];

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 'mat-1',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-fisika',
    teacher_id: 't-1',
    judul: 'Bab 4: Induksi Elektromagnetik & Hukum Faraday',
    deskripsi: 'Modul konsep dasar fluks magnetik, hukum Lenz, dan penerapan generator listrik dalam kehidupan nelayan pesisir.',
    tipe_konten: 'file',
    file_url: 'https://storage.googleapis.com/sman1batudaapantai/materi/modul_fisika_induksi_em.pdf',
    created_at: '2025-02-18T09:00:00Z',
  },
  {
    id: 'mat-2',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-fisika',
    teacher_id: 't-1',
    judul: 'Video Simulasi: Rangkaian Arus Bolak-Balik (AC)',
    deskripsi: 'Simulasi osiloskop interaktif PhET Colorado untuk menganalisis tegangan sinusoidal.',
    tipe_konten: 'link',
    file_url: 'https://phet.colorado.edu/sims/html/circuit-construction-kit-ac/latest/',
    created_at: '2025-02-20T10:30:00Z',
  },
  {
    id: 'mat-3',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-tik',
    teacher_id: 't-1',
    judul: 'Dasar Pemrograman Web & Analisis Data Berbasis SQL',
    deskripsi: 'Panduan sintaks dasar SELECT, INSERT, JOIN PostgreSQL dan konektivitas REST API.',
    tipe_konten: 'file',
    file_url: 'https://storage.googleapis.com/sman1batudaapantai/materi/panduan_sql_merdeka.pdf',
    created_at: '2025-02-21T08:00:00Z',
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg-1',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-fisika',
    teacher_id: 't-1',
    judul: 'Laporan Praktikum Induksi Medan Magnet Kumparan',
    deskripsi: 'Tuliskan hasil pengamatan praktikum kumparan selenoida, hitung GGL induksi teoritis vs pengukuran, dan buat grafik hubungan jumlah lilitan dengan tegangan.',
    file_lampiran: 'petunjuk_praktikum_ggl.pdf',
    deadline: '2025-03-05T23:59:00Z',
    bobot_nilai: 100,
    created_at: '2025-02-22T08:00:00Z',
  },
  {
    id: 'asg-2',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-tik',
    teacher_id: 't-1',
    judul: 'Tugas Proyek: Desain Skema Database Sekolah Sederhana',
    deskripsi: 'Buat ERD (Entity Relationship Diagram) sederhana untuk sistem perpustakaan atau absensi sekolah dengan minimal 4 entitas.',
    file_lampiran: 'rubrik_penilaian_erd.pdf',
    deadline: '2025-03-10T23:59:00Z',
    bobot_nilai: 100,
    created_at: '2025-02-23T11:00:00Z',
  },
];

export const INITIAL_SUBMISSIONS: Submission[] = [
  {
    id: 'subm-1',
    assignment_id: 'asg-1',
    student_id: 's-1',
    file_url: 'https://sman1batudaapantai.sch.id/tugas/fikri_hasan_praktikum_fisika.pdf',
    teks_jawaban: 'Berikut saya lampirkan laporan praktikum fisika bab induksi elektromagnetik kelompok 1.',
    submitted_at: '2025-02-23T14:30:00Z',
    nilai: 92,
    feedback: 'Analisis data sangat mendalam dan penghitungan deviasi standar sangat akurat. Pertahankan!',
    graded_at: '2025-02-24T16:00:00Z',
    graded_by: 't-1',
  },
  {
    id: 'subm-2',
    assignment_id: 'asg-1',
    student_id: 's-2',
    file_url: 'https://sman1batudaapantai.sch.id/tugas/siti_rahmawati_fisika.pdf',
    teks_jawaban: 'Laporan praktikum fisika lengkap dengan foto dokumentasi alat praktikum sekolah.',
    submitted_at: '2025-02-24T08:15:00Z',
    nilai: 88,
    feedback: 'Grafik sudah rapi, kesimpulan perhatikan kembali perumusan hukum Lenz.',
    graded_at: '2025-02-24T16:10:00Z',
    graded_by: 't-1',
  }
];

export const INITIAL_JOURNALS: TeacherJournal[] = [
  {
    id: 'jrn-1',
    teacher_id: 't-1',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-fisika',
    tanggal: '2025-02-24',
    jam_ke: '1 - 2 (07:15 - 08:45)',
    materi_diajarkan: 'Percobaan Induksi Faraday dan Transformator Step Up/Down',
    metode: 'Eksperimen Laboratorium & Diskusi Kelompok Problem-Based Learning',
    catatan: 'Siswa sangat aktif saat pengujian galvanometer. 1 siswa izin sakit (Fadly Ahmad). Alat praktikum berfungsi baik.',
    jumlah_hadir: 4,
    jumlah_absen: 1,
    created_at: '2025-02-24T09:00:00Z',
  },
  {
    id: 'jrn-2',
    teacher_id: 't-1',
    class_id: 'c-xii-mipa-1',
    subject_id: 'sub-tik',
    tanggal: '2025-02-19',
    jam_ke: '1 - 2 (07:15 - 08:45)',
    materi_diajarkan: 'Perancangan Database Relasional dan Pengenalan Supabase PostgreSQL',
    metode: 'Praktik Langsung di Lab Komputer & Studi Kasus',
    catatan: 'Jaringan internet sekolah stabil. Semua siswa berhasil membuat tabel pertama.',
    jumlah_hadir: 5,
    jumlah_absen: 0,
    created_at: '2025-02-19T09:00:00Z',
  }
];

export const INITIAL_ATTITUDES: AttitudeAssessment[] = [
  {
    id: 'attd-1',
    student_id: 's-1',
    teacher_id: 't-1',
    tanggal: '2025-02-24',
    jenis: 'spiritual',
    predikat: 'Sangat Baik',
    catatan: 'Khusyuk saat memimpin doa sebelum memulai kegiatan laboratorium dan mengingatkan rekan-rekannya.',
    created_at: '2025-02-24T09:15:00Z',
  },
  {
    id: 'attd-2',
    student_id: 's-1',
    teacher_id: 't-1',
    tanggal: '2025-02-24',
    jenis: 'sosial',
    predikat: 'Sangat Baik',
    catatan: 'Memiliki jiwa gotong royong tinggi, aktif membantu merapikan alat praktikum kelompok lain.',
    created_at: '2025-02-24T09:15:00Z',
  },
  {
    id: 'attd-3',
    student_id: 's-5',
    teacher_id: 't-1',
    tanggal: '2025-02-24',
    jenis: 'sosial',
    predikat: 'Baik',
    catatan: 'Jujur mengakui kendala keterlambatan karena perahu nelayan, kooperatif dalam kelompok praktikum.',
    created_at: '2025-02-24T09:15:00Z',
  },
];
